# Generated by Django 5.2.12 on 2026-03-17 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_code', models.CharField(max_length=64, unique=True)),
                ('zone', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(blank=True, default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('pass_tag', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(blank=True, default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользователь (метка/пропуск)',
                'verbose_name_plural': 'Пользователи (метки/пропуска)',
            },
        ),
        migrations.CreateModel(
            name='TrackedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irf_tag', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='ok', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='inventory.cell')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handouts', to='inventory.trackedobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handouts', to='inventory.usertag')),
            ],
            options={
                'verbose_name': 'Выдача на руки',
                'verbose_name_plural': 'Выдачи на руки',
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('object',), name='uniq_active_handout_per_object')],
            },
        ),
    ]
