# Generated by Django 5.2.13 on 2026-05-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_trackedobject_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Сушит прямо сейчас')),
                ('last_humidity', models.FloatField(blank=True, null=True, verbose_name='Последняя влажность, %')),
                ('last_temp', models.FloatField(blank=True, null=True, verbose_name='Последняя температура, °C')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('last_raw', models.TextField(blank=True, default='', verbose_name='Сырой ответ от ESP')),
            ],
            options={
                'verbose_name': 'Статус сушилки',
                'verbose_name_plural': 'Статус сушилки',
            },
        ),
        migrations.CreateModel(
            name='RentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(help_text='take (ожидается выдача) / return (ожидается возврат)', max_length=10, verbose_name='Режим')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сессия аренды',
                'verbose_name_plural': 'Сессии аренды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ['cell_code'], 'verbose_name': 'Ячейка', 'verbose_name_plural': 'Ячейки'},
        ),
        migrations.AlterModelOptions(
            name='handout',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Выдача', 'verbose_name_plural': 'Выдачи'},
        ),
        migrations.AlterModelOptions(
            name='trackedobject',
            options={'ordering': ['irf_tag'], 'verbose_name': 'Зонт', 'verbose_name_plural': 'Зонты'},
        ),
        migrations.AlterModelOptions(
            name='usertag',
            options={'ordering': ['pass_tag'], 'verbose_name': 'Клиент / карта', 'verbose_name_plural': 'Клиенты / карты'},
        ),
        migrations.RemoveConstraint(
            model_name='handout',
            name='uniq_active_handout_per_object',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='status',
        ),
        migrations.RemoveField(
            model_name='handout',
            name='note',
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='status',
        ),
        migrations.AddField(
            model_name='trackedobject',
            name='home_cell',
            field=models.ForeignKey(blank=True, help_text='Куда возвращать зонт по умолчанию.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_objects', to='inventory.cell', verbose_name='Домашняя ячейка'),
        ),
        migrations.AddField(
            model_name='trackedobject',
            name='is_drying',
            field=models.BooleanField(default=False, help_text='True — зонт в процессе сушки.', verbose_name='Сушится сейчас'),
        ),
        migrations.AddField(
            model_name='trackedobject',
            name='last_dried_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя сушка'),
        ),
        migrations.AddField(
            model_name='trackedobject',
            name='last_humidity',
            field=models.FloatField(blank=True, null=True, verbose_name='Последняя влажность, %'),
        ),
        migrations.AddField(
            model_name='trackedobject',
            name='last_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Последняя температура, °C'),
        ),
        migrations.AddField(
            model_name='trackedobject',
            name='needs_drying',
            field=models.BooleanField(default=False, help_text='Устанавливается при возврате зонта. Сушилка опрашивает это поле.', verbose_name='Требует сушки'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_code',
            field=models.CharField(help_text='Например: A1, A2, B1...', max_length=32, unique=True, verbose_name='Код ячейки'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='zone',
            field=models.CharField(blank=True, default='', help_text='Например: Главный вход, Кафетерий', max_length=64, verbose_name='Зона / локация'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='issued_at',
            field=models.DateTimeField(verbose_name='Выдан'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to='inventory.trackedobject', verbose_name='Зонт'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Возвращён'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to='inventory.usertag', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='trackedobject',
            name='cell',
            field=models.ForeignKey(blank=True, help_text='Где зонт сейчас. NULL — на руках у клиента.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_objects', to='inventory.cell', verbose_name='Текущая ячейка'),
        ),
        migrations.AlterField(
            model_name='trackedobject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='trackedobject',
            name='irf_tag',
            field=models.CharField(max_length=128, unique=True, verbose_name='IRF-метка (UID зонта)'),
        ),
        migrations.AlterField(
            model_name='trackedobject',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название / номер зонта'),
        ),
        migrations.AlterField(
            model_name='trackedobject',
            name='state',
            field=models.CharField(default='ok', help_text='ok / broken / lost ...', max_length=32, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='pass_tag',
            field=models.CharField(help_text="Например: '93 94 31 30'", max_length=128, unique=True, verbose_name='UID карты'),
        ),
        migrations.AddField(
            model_name='rentsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.usertag', verbose_name='Клиент'),
        ),
    ]
